info:
  contact: {}
paths:
  /dashboard/GetTblqueMonthlyReport:
    get:
      description: display username, number, department, counter, called date, issued
        time, called time filter by start and end date and department id
      responses:
        "201":
          description: Created
      summary: GetTblqueMonthlyReport
      tags:
      - '[]models.Tblquelog'
swagger: "2.0"
